sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  
  # add steps 1-4
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl 
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-287615   <- this is a project ID
  - gcloud config set compute/zone us-central1-a  <- zone where your cluster located
  - gcloud container clusters get-credentials multi-cluster 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t alexgure/react-test -f -f ./client/Dockerfile.dev ./client

script:
  - docker run alexgure/react-test npm test -- --coverage  

deploy:
  provider: script
  # create deploy.sh file in out project folder with instructions how to deploy. 
  script: bash ./deploy.sh
  on:
    branch: master
	
